# Generated by Django 4.0.5 on 2022-07-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerID', models.IntegerField()),
                ('CustomerName', models.CharField(max_length=50)),
                ('OrderNo', models.IntegerField()),
                ('ShareName', models.CharField(max_length=50)),
                ('Buy_SellPrice', models.IntegerField()),
                ('NumberOfShares', models.IntegerField()),
                ('OrderDate', models.DateField()),
                ('OrderTime', models.TimeField()),
            ],
        ),
    ]
